# Quick intro to `numpy`
### MCS 275 Spring 2022 - David Dumas

This is a quick tour of some `numpy` features.  For more detail see:
* [Chapter 2 of VanderPlas](https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html)
* [The numpy documentation](https://numpy.org/doc/stable/)

## Import the module

None of the code below will work without this!

In [1]:
import numpy as np
np.__version__

'1.22.2'

## Making and using arrays

[List of built-in dtypes](https://numpy.org/doc/stable/reference/arrays.scalars.html#arrays-scalars-built-in).

In [74]:
# all zeros, specified shape
np.zeros( (2,3) )

array([[0., 0., 0.],
       [0., 0., 0.]])

In [75]:
# all ones, specified shape
np.ones( (8,) )

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# array with every entry equal to a given constant
np.full( (3,3), 1.7 )  # shape, value

In [ ]:
A = np.ones( (4,4) )
A.ndim  # the dimension of A

In [ ]:
A.shape # the shape of A

In [ ]:
A.size # the number of elements in A

In [ ]:
A.dtype # the data type (np.ones gives float64 by default)

In [ ]:
B = np.full( (2,3), 6 )  # Python int given, converted to int64
B.dtype

In [ ]:
# Build array from an iterable
C = np.array( [[5,6,7,8],[9,10,11,12]] )

In [ ]:
print(C.ndim)
print(C.dtype)
print(C.size)

In [ ]:
# np.random.random(shape) gives array of uniformly distributed
# random floats 0<=x<1
np.random.random((5,8))

In [ ]:
np.ones((2,2),dtype="bool")  # numpy supports boolean arrays
# coerces 0 to False and 1 to True

In [76]:
Abyte = np.zeros((4,3),dtype="uint8")  # Array of 1-byte values
Abyte

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint8)

In [77]:
Abyte[1,1] = 10
Abyte[3,2] = 300
Abyte

array([[ 0,  0,  0],
       [ 0, 10,  0],
       [ 0,  0,  0],
       [ 0,  0, 44]], dtype=uint8)

### Arithmetic progressions

* `np.arange` is start, stop, step
* `np.linspace` is first, last, nstep

In [39]:
np.arange(3,13,2) # stop will not be included

array([ 3,  5,  7,  9, 11])

In [40]:
np.arange(3,5,0.1)

array([3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2,
       4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [43]:
np.linspace(2,6,4)

array([2.        , 3.33333333, 4.66666667, 6.        ])

## Accessing elements (indexing and slices)

In [83]:
A = np.array(range(24)).reshape((4,6))   # 0..23 in a vector, but then convert to 4x6 matrix
v = np.arange(1,5,1.2) # vector (array with ndim=1)

In [84]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
v

In [ ]:
v[1] # element at index 1 (zero-based)

In [ ]:
v[-2] # second to last element

In [ ]:
A[2,0]  # row 2, column 0

In [85]:
A[:,2]  # column 2 of A  (remember, 0-based numbering!)
# I think of this as A[anything,2]

array([ 2,  8, 14, 20])

In [86]:
A[1,:]  # row 1 of A
# I think of this as A[1,anything]

array([ 6,  7,  8,  9, 10, 11])

In [87]:
A[1] # another way to specify row 1 of A
# missing indices are treated as ":"

array([ 6,  7,  8,  9, 10, 11])

In [ ]:
A[::2,1:3]  # all rows of even index, columns 1 and 2

## Mutability

## Vector math

Vectors are 1D arrays

```
building
scalar mult
vector addition
dot product
multiplication not what you want
np.linalg.norm
```

## Matrices

Matrices are 2D arrays

```
eye
transpose
dot with vector
np.linalg.det
```

## Ufuncs

reciprocal, power, sin, cos

## Broadcasting
* Broadcasting rules described [here](https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png) (from [Chapter 2 of VanderPlas](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html))

## Aggregations

```
min
max
sum
mean
any
all
```

## Pillow integration

* `np.array(img)` just works, if `img` is a `PIL.Image` object
* Use `PIL.Image.fromarray(A)` to make an image from an array
    * Shape `(height,width)` and dtype `uint8` for grayscale
    * Shaape `(height,width,3)` and dtype `uint8` for color (last axis is red, green, blue)